### ISSUE TITLE
Login page / Page de connexion

### ISSUE THREAD

**Issue by JessyFra** [TolMen/OCProject6#9]
**_English version_**

Description : Implement the login page for users

Tasks :

- Create the login page
- Expand the form (username and password)
- Manage authentication and error messages in case of failure
- Add link to password reset page

\
**_Version française_**

Description : Implémenter la page de connexion pour les utilisateurs

Tâches :

- Créer la page de connexion
- Développer le formulaire (nom d’utilisateur et mot de passe)
- Gérer l'authentification et les messages d’erreur en cas d’échec
- Ajouter le lien vers la page de réinitialisation du mot de passe

**Comment by JessyFra** [comment]
Stress points : 7/10 points

**Comment by JessyFra** [comment]
**_English_**
Using the "symfony console make:auth" command to configure the login form

**_Français_**
Utilisation de la commande "symfony console make:auth" pour paramétrer le formulaire de connexion

**Comment by JessyFra** [comment]
**_English_**
Changing the route after login in the "LoginFormAuthenticator.php" file

**_Français_**
Modification de la route une fois la connexion effectuée dans le fichier "LoginFormAuthenticator.php"

**Comment by TolMen** [comment]
**_English_**
Using the "symfony console make:reset-password" command to create all the files needed to run the function

**_Français_**
Utilisation de la commande "symfony console make:reset-password" pour créer tous les fichiers nécessaires à l'exécution de la fonction
